tap "fwartner/tap"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
tap "sidneys/homebrew"

# libs
brew "lz4"
brew "libssh2"
brew "readline"
brew "aria2"
brew "automake"
brew "freetype"
brew "glib"
brew "pkg-config"
brew "ccache"
brew "cdrtools"
brew "cmake"
brew "dpkg"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "opus"
brew "libvpx"
brew "ffmpeg@4"
brew "gnupg"
brew "gobject-introspection"
brew "gperf"
brew "gsl"
brew "libtool"
brew "imagemagick"
brew "libmicrohttpd"
brew "libssh"
brew "libusbmuxd"
brew "mkcert"
brew "nghttp2"
brew "ninja"
brew "nss"
brew "numpy"
brew "vtk"
brew "opencv"
brew "osslsigncode"
brew "pinentry-mac"
brew "portaudio"
brew "qemu"
brew "srtp"
brew "wimlib"
brew "winetricks"
brew "yasm"

# langs
brew "openjdk"
brew "node"
brew "go"
brew "guile"

# tools
brew "postgresql@14"
brew "vegeta"
brew "watch"
brew "telnet"
brew "fakeroot"
brew "htop"
brew "git"
brew "git-lfs"
brew "glab"
brew "jq"
brew "nvm"
brew "mackup"
brew "mas"
brew "tmux"
brew "tree"
brew "wget"
brew "ipython"
brew "pyenv"
brew "pipenv"
brew "poetry"
brew "yarn"
brew "mockery"
brew "mongodb/brew/mongodb-community-shell"
brew "mongodb/brew/mongodb-database-tools"

# casks
# TODO AirPods Sound Quality Fixer https://github.com/stormychel/https-github.com-stormychel-airpodssoundqualityfixer
cask "ngrok"
cask "hiddenbar"
cask "maccy"
cask "grammarly-desktop"
cask "1password"
cask "raycast"
cask "the-unarchiver"
cask "monitorcontrol"

# soft
cask "audacity"
cask "another-redis-desktop-manager"
cask "setapp"
cask "db-browser-for-sqlite"
cask "discord"
cask "docker"
cask "element"
cask "hex-fiend"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "grandperspective"
cask "deepl"
# TODO Hopper Disassembler https://www.hopperapp.com/download
cask "ilspy"
cask "insomnia"
cask "iterm2"
cask "jetbrains-toolbox"
cask "obs"
cask "poedit"
cask "obsidian"
# cask "proxyman" # install from setapp
cask "mongodb-compass"
cask "slack"
cask "spotify"
cask "telegram"
# TODO TinkerTool https://www.bresink.com/osx/0TinkerTool/download.php
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "wireshark"
cask "wine-crossover"
cask "zoom"

# App Store
mas "AdBlock Pro", id: 1018301773
mas "GoodNotes", id: 1444383602
mas "iStat Menus", id: 1319778037
mas "Magnet", id: 441258766
mas "Spark", id: 1176895641
mas "Recess", id: 621451282
mas "TextSniper", id: 1528890965
mas "Xcode", id: 497799835
