tap "fwartner/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
tap "sidneys/homebrew"
tap "rbenv/tap"
tap "datadog/lapdog"

# libs
brew "lz4"
brew "libssh2"
brew "readline"
brew "aria2"
brew "automake"
brew "freetype"
brew "glib"
brew "pkg-config"
brew "pkgconf"
brew "ccache"
brew "cdrtools"
brew "cmake"
brew "dpkg"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "opus"
brew "libvpx"
brew "gnupg"
brew "gobject-introspection"
brew "gperf"
brew "gsl"
brew "libtool"
brew "imagemagick"
brew "libmicrohttpd"
brew "libssh"
brew "libusbmuxd"
brew "mkcert"
brew "nghttp2"
brew "ninja"
brew "nss"
brew "numpy"
brew "vtk"
brew "opencv"
brew "osslsigncode"
brew "pinentry-mac"
brew "portaudio"
brew "qemu"
brew "srtp"
brew "wimlib"
brew "winetricks"
brew "yasm"
brew "rbenv/tap/openssl@1.1"

# langs
brew "openjdk"
brew "node"
brew "go"
brew "guile"
brew "rustup"
brew "gcc"
brew "llvm"

# tools
brew "cloc"
brew "ffmpeg"
brew "postgresql"
brew "vegeta"
brew "watch"
brew "telnet"
brew "fakeroot"
brew "htop"
brew "git"
brew "git-lfs"
brew "glab"
brew "jq"
brew "nvm"
brew "mackup"
brew "mas"
brew "tmux"
brew "tree"
brew "wget"
brew "ipython"
brew "pyenv"
brew "pipenv"
brew "poetry"
brew "uv"
brew "yarn"
brew "mockery"
brew "direnv"
brew "tesseract"
brew "autojump"
brew "bat"
brew "datadog/lapdog/lapdog"
brew "mongodb/brew/mongodb-community-shell"
brew "mongodb/brew/mongodb-database-tools"

# casks
cask "ngrok"
cask "hiddenbar"
cask "1password"
cask "raycast"
cask "the-unarchiver"
cask "monitorcontrol"
cask "mac-mouse-fix@2"
cask "logitech-g-hub"

# AI
cask "codex"
cask "claude-code"

# soft
cask "audacity"
cask "another-redis-desktop-manager"
cask "db-browser-for-sqlite"
cask "discord"
cask "orbstack"
cask "hex-fiend"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "deepl"
# TODO Hopper Disassembler https://www.hopperapp.com/download
cask "ilspy"
cask "insomnia"
cask "iterm2"
cask "obs"
cask "poedit"
cask "obsidian"
cask "mongodb-compass"
cask "slack"
cask "spotify"
# TODO TinkerTool https://www.bresink.com/osx/0TinkerTool/download.php
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "mitmproxy"
cask "zoom"

# App Store
mas "uBlock Origin Lite", id: 6745342698
mas "Goodnotes", id: 1444383602
mas "iStat Menus", id: 1319778037
mas "Magnet", id: 441258766
mas "TextSniper", id: 1528890965
mas "Xcode", id: 497799835
mas "Tailscale", id: 1475387142
mas "DaisyDisk", id: 411643860
